version: "2"
services:
  webserver:
    image: nginx:alpine
    ports:
      - "81:80"
    volumes:
      - ./data/overviewer/worlds:/usr/share/nginx/html

  overviewer:
    build: overviewer
    volumes:
      - ./data/minecraft/worlds/josh:/minecraft/world
      - ./data/overviewer/worlds/josh:/overviewer/world
      - ./data/overviewer/overviewer.py:/overviewer/overviewer.py
    environment: 
      MAPS_API_KEY: "AIzaSyCXPdXkdxf5nFLtjEGl7gQ2KzGiUEg9p6M"
      TEXTURES_VERSION: "1.10"


  nodemc:
    build: NodeMC
    ports: 
      - "3000:3000"
      - "25565:25565"
    environment:
      # api key for access to NodeMC
      API_KEY: "3808e65d80bbe3fe373485c30f5dd830"

    volumes:
      - ./data/nodemc/jars/eula.txt:/usr/src/NodeMC/eula.txt
      - ./data/nodemc/jars:/minecraft_jars
      - ./data/nodemc/minecraft_home/properties.json:/usr/src/NodeMC/server_files/properties.json
      - ./data/nodemc/minecraft_home/server.properties:/minecraft/server.properties
      #- ./data/nodemc/minecraft_home:/minecraft

      # world data - could also be in minecraft_home above?
      - ./data/minecraft/worlds/josh:/minecraft/world

      # custom Main.js
      - ./NodeMC/CORE/Main.js:/usr/src/NodeMC/Main.js

