version: "2"
services:
  webserver:
    image: nginx:alpine
    ports:
      - "81:80"
    volumes:
      - ./data/overviewer/worlds:/usr/share/nginx/html

  overviewer:
    build: overviewer
    volumes:
      - ./data/minecraft/worlds/josh:/minecraft/worlds/josh
      - ./data/overviewer/worlds/josh:/overviewer/worlds/josh
      - ./data/overviewer/textures:/overviewer/textures
    environment: 
      WORLD: josh
      TEXTURES_VERSION: "1.10"
      MAPS_API_KEY: "AIzaSyCXPdXkdxf5nFLtjEGl7gQ2KzGiUEg9p6M"

  nodemc:
    build: NodeMC
    ports: 
      - "3000:3000"
      - "25565:25565"
    environment:
      API_KEY: "3808e65d80bbe3fe373485c30f5dd830"
    volumes:
      - ./data/nodemc/jars/eula.txt:/usr/src/NodeMC/eula.txt
      - ./data/nodemc/jars:/nodemc_data
      - ./data/nodemc/settings/properties.json:/usr/src/NodeMC/server_files/properties.json
      - ./data/nodemc/settings/server.properties:/usr/src/NodeMC/server.properties

      - ./NodeMC/CORE/Main.js:/usr/src/NodeMC/Main.js

      - ./data/minecraft/worlds/josh:/usr/src/NodeMC/world
